### ISSUE TITLE
日志为什么不做成异步处理呢？

### ISSUE THREAD

**Issue by huxxx** [qqxx6661/systemLog#1]
大佬：
   你好，请教下日志处理为什么不做成异步呢？

**Comment by qqxx6661** [comment]
你好~单纯是当时赶时间，精力有限，就先简陋地写了个出来用了。
之后会优化成异步的，如果你愿意可以直接写一个pr，这里：
https://github.com/qqxx6661/logRecord/pulls

**Comment by huxxx** [comment]
作者，你好，已经提交pr

**Comment by qqxx6661** [comment]
好的，感谢哈。我还在加班 T_T 晚点看

**Comment by kaitezhan** [comment]
> 好的，感谢哈。我还在加班 T_T 晚点看

请问什么时候能上传到maven中央仓库呢？现在无法引入

**Comment by kaitezhan** [comment]
> > 好的，感谢哈。我还在加班 T_T 晚点看
> 
> 请问什么时候能上传到maven中央仓库呢？现在无法引入



> 好的，感谢哈。我还在加班 T_T 晚点看

请问什么时候能上传到阿里云的maven仓库？

**Comment by qqxx6661** [comment]
<dependency>
    <groupId>cn.monitor4all</groupId>
    <artifactId>log-record-starter</artifactId>
    <version>{最新版本号}</version>
</dependency>

maven中央仓库已经上了，在这里查所有版本：

https://search.maven.org/artifact/cn.monitor4all/log-record-starter

最新的版本号是1.0.7  

如果阿里云的maven中心拉不到，应该是阿里云的镜像问题。
